services:
  # Backend API Service
  - type: web
    name: mukul-portfolio-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: JWT_SECRET
    #   generateValue: true
    # - key: EMAIL_USER
    #   value: your-email@gmail.com
    # - key: EMAIL_PASS
    #   value: your-app-password

  # Frontend Static Site
  - type: web
    name: mukul-portfolio-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
